/* Generated by Nimrod Compiler v0.9.2 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, helloInit)(void);
N_NOINLINE(void, helloDatInit)(void);
STRING_LITERAL(TMP120, "Hello, world!", 13);
extern TFrame* frameptr_10225;

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	helloDatInit();
	initStackBottom();
	systemInit();
	helloInit();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_10225;
	frameptr_10225 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_10225 = (*frameptr_10225).prev;
}
N_NOINLINE(void, helloInit)(void) {
	nimfr("hello", "hello.nim")
	nimln(1, "hello.nim");
	printf("%s\012", (((NimStringDesc*) &TMP120))->data);
	popFrame();
}

N_NOINLINE(void, helloDatInit)(void) {
}

