/* Generated by Nimrod Compiler v0.9.2 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: FreeBSD, i386, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/lib/nimrod -o usr/home/matt/MyProjects/Challenges-Nimrod/Numbers/calc/nimcache/strutils.o usr/home/matt/MyProjects/Challenges-Nimrod/Numbers/calc/nimcache/strutils.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct einvalidvalue1053 einvalidvalue1053;
typedef struct esynch1029 esynch1029;
typedef struct E_Base E_Base;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell34049 tcell34049;
typedef struct tcellseq34065 tcellseq34065;
typedef struct tgcheap36016 tgcheap36016;
typedef struct tcellset34061 tcellset34061;
typedef struct tpagedesc34057 tpagedesc34057;
typedef struct tmemregion17610 tmemregion17610;
typedef struct tsmallchunk16843 tsmallchunk16843;
typedef struct tllchunk17604 tllchunk17604;
typedef struct tbigchunk16845 tbigchunk16845;
typedef struct tintset16818 tintset16818;
typedef struct ttrunk16814 ttrunk16814;
typedef struct tavlnode17608 tavlnode17608;
typedef struct tgcstat36014 tgcstat36014;
typedef struct tbasechunk16841 tbasechunk16841;
typedef struct tfreecell16833 tfreecell16833;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY891) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY891 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct E_Base {
  TNimObject Sup;
E_Base* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct esynch1029 {
  E_Base Sup;
};
struct einvalidvalue1053 {
  esynch1029 Sup;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell34049 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq34065 {
NI Len;
NI Cap;
tcell34049** D;
};
struct tcellset34061 {
NI Counter;
NI Max;
tpagedesc34057* Head;
tpagedesc34057** Data;
};
typedef tsmallchunk16843* TY17622[512];
typedef ttrunk16814* ttrunkbuckets16816[256];
struct tintset16818 {
ttrunkbuckets16816 Data;
};
struct tmemregion17610 {
NI Minlargeobj;
NI Maxlargeobj;
TY17622 Freesmallchunks;
tllchunk17604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk16845* Freechunkslist;
tintset16818 Chunkstarts;
tavlnode17608* Root;
tavlnode17608* Deleted;
tavlnode17608* Last;
tavlnode17608* Freeavlnodes;
};
struct tgcstat36014 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap36016 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq34065 Zct;
tcellseq34065 Decstack;
tcellset34061 Cycleroots;
tcellseq34065 Tempstack;
NI Recgclock;
tmemregion17610 Region;
tgcstat36014 Stat;
};
typedef NI TY16821[16];
struct tpagedesc34057 {
tpagedesc34057* Next;
NI Key;
TY16821 Bits;
};
struct tbasechunk16841 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk16843 {
  tbasechunk16841 Sup;
tsmallchunk16843* Next;
tsmallchunk16843* Prev;
tfreecell16833* Freelist;
NI Free;
NI Acc;
NF64 Data;
};
struct tllchunk17604 {
NI Size;
NI Acc;
tllchunk17604* Next;
};
struct tbigchunk16845 {
  tbasechunk16841 Sup;
tbigchunk16845* Next;
tbigchunk16845* Prev;
NI Align;
NF64 Data;
};
struct ttrunk16814 {
ttrunk16814* Next;
NI Key;
TY16821 Bits;
};
typedef tavlnode17608* TY17614[2];
struct tavlnode17608 {
TY17614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell16833 {
tfreecell16833* Next;
NI Zerofield;
};
N_NIMCALL(NI, npuParseFloat)(NimStringDesc* s, NF* number, NI start);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell34049*, usrtocell_37443)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_38602)(tcell34049* c);
N_NOINLINE(void, addzct_37415)(tcellseq34065* s, tcell34049* c);
N_NIMCALL(void, raiseException)(E_Base* e, NCSTRING ename);
STRING_LITERAL(TMP146, "invalid float: ", 15);
extern TNimType NTI70625; /* ref EInvalidValue */
extern TNimType NTI1053; /* EInvalidValue */
extern TFrame* frameptr_10225;
extern tgcheap36016 gch_36042;

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) (&(*dest).data[((*dest).Sup.len)- 0])), ((NCSTRING) ((*src).data)), (NI32)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_10225;
	frameptr_10225 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_10225 = (*frameptr_10225).prev;
}

static N_INLINE(tcell34049*, usrtocell_37443)(void* usr) {
	tcell34049* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(106, "gc.nim");
	nimln(106, "gc.nim");
	nimln(106, "gc.nim");
	result = ((tcell34049*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell34049))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_38602)(tcell34049* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(184, "gc.nim");
	addzct_37415(&gch_36042.Zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(236, "gc.nim");
	nimln(696, "system.nim");
	nimln(696, "system.nim");
	if (!!((src == NIM_NIL))) goto LA2;
	{
		tcell34049* c;
		nimln(237, "gc.nim");
		c = usrtocell_37443(src);
		nimln(157, "gc.nim");
		(*c).Refcount += 8;
	}
	LA2: ;
	nimln(239, "gc.nim");
	nimln(696, "system.nim");
	nimln(696, "system.nim");
	if (!!(((*dest) == NIM_NIL))) goto LA6;
	{
		tcell34049* c;
		nimln(240, "gc.nim");
		c = usrtocell_37443((*dest));
		nimln(241, "gc.nim");
		nimln(155, "gc.nim");
		(*c).Refcount -= 8;
		nimln(156, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA10;
		{
			nimln(242, "gc.nim");
			rtladdzct_38602(c);
		}
		LA10: ;
	}
	LA6: ;
	nimln(243, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s) {
	NF result;
	NI l;
	NIM_BOOL LOC2;
	nimfr("ParseFloat", "strutils.nim")
	result = 0;
	nimln(368, "strutils.nim");
	l = npuParseFloat(s, &result, 0);
	nimln(369, "strutils.nim");
	nimln(369, "strutils.nim");
	nimln(696, "system.nim");
	nimln(696, "system.nim");
	nimln(369, "strutils.nim");
	LOC2 = !((l == s->Sup.len));
	if (LOC2) goto LA3;
	nimln(369, "strutils.nim");
	LOC2 = (l == 0);
	LA3: ;
	if (!LOC2) goto LA4;
	{
		einvalidvalue1053* e_70624;
		NimStringDesc* LOC7;
		e_70624 = 0;
		nimln(1785, "system.nim");
		e_70624 = (einvalidvalue1053*) newObj((&NTI70625), sizeof(einvalidvalue1053));
		(*e_70624).Sup.Sup.Sup.m_type = (&NTI1053);
		nimln(1786, "system.nim");
		nimln(370, "strutils.nim");
		LOC7 = 0;
		LOC7 = rawNewString(s->Sup.len + 15);
appendString(LOC7, ((NimStringDesc*) &TMP146));
appendString(LOC7, s);
		asgnRefNoCycle((void**) &(*e_70624).Sup.Sup.message, LOC7);
		nimln(370, "strutils.nim");
		raiseException((E_Base*)e_70624, "EInvalidValue");
	}
	LA4: ;
	popFrame();
	return result;
}
N_NOINLINE(void, strutilsInit)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

N_NOINLINE(void, strutilsDatInit)(void) {
}

