/* Generated by Nimrod Compiler v0.9.2 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: FreeBSD, i386, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/lib/nimrod -o /usr/home/matt/MyProjects/Challenges-Nimrod/Numbers/calc/nimcache/parseutils.o /usr/home/matt/MyProjects/Challenges-Nimrod/Numbers/calc/nimcache/parseutils.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
N_NIMCALL(NI, npuParseBiggestFloat)(NimStringDesc* s, NF64* number, NI start);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_10225;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	NIM_BOOL LOC2;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	LOC2 = (0 <= (NI)(result ^ a));
	if (LOC2) goto LA3;
	LOC2 = (0 <= (NI)(result ^ b));
	LA3: ;
	if (!LOC2) goto LA4;
	{
		goto BeforeRet;
	}
	LA4: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	NIM_BOOL LOC2;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	LOC2 = (0 <= (NI)(result ^ a));
	if (LOC2) goto LA3;
	LOC2 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
	LA3: ;
	if (!LOC2) goto LA4;
	{
		goto BeforeRet;
	}
	LA4: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_10225;
	frameptr_10225 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_10225 = (*frameptr_10225).prev;
}

N_NIMCALL(NI, npuParseBiggestFloat)(NimStringDesc* s, NF64* number, NI start) {
	NI result;
	NF esign;
	NF sign;
	NI i;
	NI exponent;
	NI flags;
	NIM_BOOL LOC9;
	NIM_BOOL LOC31;
	NF hd;
	NI j_68429;
	NI res_68433;
	NI TMP144;
	nimfr("parseBiggestFloat", "parseutils.nim")
	result = 0;
	nimln(224, "parseutils.nim");
	esign = 1.0000000000000000e+00;
	nimln(225, "parseutils.nim");
	sign = 1.0000000000000000e+00;
	nimln(226, "parseutils.nim");
	i = start;
	exponent = 0;
	flags = 0;
	nimln(229, "parseutils.nim");
	(*number) = 0.0;
	nimln(230, "parseutils.nim");
	nimln(230, "parseutils.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA2;
	{
		nimln(230, "parseutils.nim");
		i = addInt(i, 1);
	}
	goto LA1;
	LA2: ;
	nimln(231, "parseutils.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	if (!((NU8)(s->data[i]) == (NU8)(45))) goto LA5;
	{
		nimln(232, "parseutils.nim");
		sign = -1.0000000000000000e+00;
		nimln(233, "parseutils.nim");
		i = addInt(i, 1);
	}
	goto LA1;
	LA5: ;
	LA1: ;
	nimln(234, "parseutils.nim");
	nimln(234, "parseutils.nim");
	nimln(234, "parseutils.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	LOC9 = ((NU8)(s->data[i]) == (NU8)(78));
	if (LOC9) goto LA10;
	nimln(234, "parseutils.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	LOC9 = ((NU8)(s->data[i]) == (NU8)(110));
	LA10: ;
	if (!LOC9) goto LA11;
	{
		NIM_BOOL LOC15;
		NI TMP125;
		NI TMP126;
		nimln(235, "parseutils.nim");
		nimln(235, "parseutils.nim");
		nimln(235, "parseutils.nim");
		nimln(235, "parseutils.nim");
		TMP125 = addInt(i, 1);
		if ((NU)((NI32)(TMP125)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC15 = ((NU8)(s->data[(NI32)(TMP125)]) == (NU8)(65));
		if (LOC15) goto LA16;
		nimln(235, "parseutils.nim");
		nimln(235, "parseutils.nim");
		TMP126 = addInt(i, 1);
		if ((NU)((NI32)(TMP126)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC15 = ((NU8)(s->data[(NI32)(TMP126)]) == (NU8)(97));
		LA16: ;
		if (!LOC15) goto LA17;
		{
			NIM_BOOL LOC21;
			NI TMP127;
			NI TMP128;
			nimln(236, "parseutils.nim");
			nimln(236, "parseutils.nim");
			nimln(236, "parseutils.nim");
			nimln(236, "parseutils.nim");
			TMP127 = addInt(i, 2);
			if ((NU)((NI32)(TMP127)) > (NU)(s->Sup.len)) raiseIndexError();
			LOC21 = ((NU8)(s->data[(NI32)(TMP127)]) == (NU8)(78));
			if (LOC21) goto LA22;
			nimln(236, "parseutils.nim");
			nimln(236, "parseutils.nim");
			TMP128 = addInt(i, 2);
			if ((NU)((NI32)(TMP128)) > (NU)(s->Sup.len)) raiseIndexError();
			LOC21 = ((NU8)(s->data[(NI32)(TMP128)]) == (NU8)(110));
			LA22: ;
			if (!LOC21) goto LA23;
			{
				NI TMP129;
				nimln(237, "parseutils.nim");
				nimln(729, "system.nim");
				nimln(729, "system.nim");
				nimln(237, "parseutils.nim");
				TMP129 = addInt(i, 3);
				if ((NU)((NI32)(TMP129)) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!((((NU8)(s->data[(NI32)(TMP129)])) >= ((NU8)(97)) && ((NU8)(s->data[(NI32)(TMP129)])) <= ((NU8)(122)) || ((NU8)(s->data[(NI32)(TMP129)])) >= ((NU8)(65)) && ((NU8)(s->data[(NI32)(TMP129)])) <= ((NU8)(90)) || ((NU8)(s->data[(NI32)(TMP129)])) >= ((NU8)(48)) && ((NU8)(s->data[(NI32)(TMP129)])) <= ((NU8)(57)) || ((NU8)(s->data[(NI32)(TMP129)])) == ((NU8)(95))))) goto LA27;
				{
					NI TMP130;
					NI TMP131;
					nimln(238, "parseutils.nim");
					(*number) = NAN;
					nimln(239, "parseutils.nim");
					nimln(239, "parseutils.nim");
					nimln(239, "parseutils.nim");
					nimln(239, "parseutils.nim");
					TMP130 = addInt(i, 3);
					TMP131 = subInt((NI32)(TMP130), start);
					result = (NI32)(TMP131);
					goto BeforeRet;
				}
				LA27: ;
			}
			LA23: ;
		}
		LA17: ;
		nimln(240, "parseutils.nim");
		nimln(240, "parseutils.nim");
		result = 0;
		goto BeforeRet;
	}
	LA11: ;
	nimln(241, "parseutils.nim");
	nimln(241, "parseutils.nim");
	nimln(241, "parseutils.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	LOC31 = ((NU8)(s->data[i]) == (NU8)(73));
	if (LOC31) goto LA32;
	nimln(241, "parseutils.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	LOC31 = ((NU8)(s->data[i]) == (NU8)(105));
	LA32: ;
	if (!LOC31) goto LA33;
	{
		NIM_BOOL LOC37;
		NI TMP132;
		NI TMP133;
		nimln(242, "parseutils.nim");
		nimln(242, "parseutils.nim");
		nimln(242, "parseutils.nim");
		nimln(242, "parseutils.nim");
		TMP132 = addInt(i, 1);
		if ((NU)((NI32)(TMP132)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC37 = ((NU8)(s->data[(NI32)(TMP132)]) == (NU8)(78));
		if (LOC37) goto LA38;
		nimln(242, "parseutils.nim");
		nimln(242, "parseutils.nim");
		TMP133 = addInt(i, 1);
		if ((NU)((NI32)(TMP133)) > (NU)(s->Sup.len)) raiseIndexError();
		LOC37 = ((NU8)(s->data[(NI32)(TMP133)]) == (NU8)(110));
		LA38: ;
		if (!LOC37) goto LA39;
		{
			NIM_BOOL LOC43;
			NI TMP134;
			NI TMP135;
			nimln(243, "parseutils.nim");
			nimln(243, "parseutils.nim");
			nimln(243, "parseutils.nim");
			nimln(243, "parseutils.nim");
			TMP134 = addInt(i, 2);
			if ((NU)((NI32)(TMP134)) > (NU)(s->Sup.len)) raiseIndexError();
			LOC43 = ((NU8)(s->data[(NI32)(TMP134)]) == (NU8)(70));
			if (LOC43) goto LA44;
			nimln(243, "parseutils.nim");
			nimln(243, "parseutils.nim");
			TMP135 = addInt(i, 2);
			if ((NU)((NI32)(TMP135)) > (NU)(s->Sup.len)) raiseIndexError();
			LOC43 = ((NU8)(s->data[(NI32)(TMP135)]) == (NU8)(102));
			LA44: ;
			if (!LOC43) goto LA45;
			{
				NI TMP136;
				nimln(244, "parseutils.nim");
				nimln(729, "system.nim");
				nimln(729, "system.nim");
				nimln(244, "parseutils.nim");
				TMP136 = addInt(i, 3);
				if ((NU)((NI32)(TMP136)) > (NU)(s->Sup.len)) raiseIndexError();
				if (!!((((NU8)(s->data[(NI32)(TMP136)])) >= ((NU8)(97)) && ((NU8)(s->data[(NI32)(TMP136)])) <= ((NU8)(122)) || ((NU8)(s->data[(NI32)(TMP136)])) >= ((NU8)(65)) && ((NU8)(s->data[(NI32)(TMP136)])) <= ((NU8)(90)) || ((NU8)(s->data[(NI32)(TMP136)])) >= ((NU8)(48)) && ((NU8)(s->data[(NI32)(TMP136)])) <= ((NU8)(57)) || ((NU8)(s->data[(NI32)(TMP136)])) == ((NU8)(95))))) goto LA49;
				{
					NI TMP137;
					NI TMP138;
					nimln(245, "parseutils.nim");
					nimln(245, "parseutils.nim");
					(*number) = ((NF64) ((INF * sign)));
					nimln(246, "parseutils.nim");
					nimln(246, "parseutils.nim");
					nimln(246, "parseutils.nim");
					nimln(246, "parseutils.nim");
					TMP137 = addInt(i, 3);
					TMP138 = subInt((NI32)(TMP137), start);
					result = (NI32)(TMP138);
					goto BeforeRet;
				}
				LA49: ;
			}
			LA45: ;
		}
		LA39: ;
		nimln(247, "parseutils.nim");
		nimln(247, "parseutils.nim");
		result = 0;
		goto BeforeRet;
	}
	LA33: ;
	nimln(248, "parseutils.nim");
	while (1) {
		NI TMP139;
		nimln(728, "system.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA52;
		nimln(250, "parseutils.nim");
		nimln(250, "parseutils.nim");
		flags = (NI)(flags | 1);
		nimln(251, "parseutils.nim");
		nimln(251, "parseutils.nim");
		nimln(251, "parseutils.nim");
		nimln(251, "parseutils.nim");
		nimln(251, "parseutils.nim");
		nimln(251, "parseutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		TMP139 = subInt(((NI) (((NU8)(s->data[i])))), 48);
		(*number) = ((NF64) (((((NF) ((*number))) * 1.0000000000000000e+01) + ((double) (((NI) ((NI32)(TMP139))))))));
		nimln(252, "parseutils.nim");
		i = addInt(i, 1);
		nimln(253, "parseutils.nim");
		while (1) {
			nimln(253, "parseutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA53;
			nimln(253, "parseutils.nim");
			i = addInt(i, 1);
		} LA53: ;
	} LA52: ;
	nimln(255, "parseutils.nim");
	nimln(255, "parseutils.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	if (!((NU8)(s->data[i]) == (NU8)(46))) goto LA55;
	{
		NF hd;
		nimln(256, "parseutils.nim");
		hd = 1.0000000000000000e+00;
		nimln(257, "parseutils.nim");
		i = addInt(i, 1);
		nimln(258, "parseutils.nim");
		while (1) {
			NI TMP140;
			nimln(728, "system.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA58;
			nimln(260, "parseutils.nim");
			nimln(260, "parseutils.nim");
			flags = (NI)(flags | 2);
			nimln(261, "parseutils.nim");
			nimln(261, "parseutils.nim");
			nimln(261, "parseutils.nim");
			nimln(261, "parseutils.nim");
			nimln(261, "parseutils.nim");
			nimln(261, "parseutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			TMP140 = subInt(((NI) (((NU8)(s->data[i])))), 48);
			(*number) = ((NF64) (((((NF) ((*number))) * 1.0000000000000000e+01) + ((double) (((NI) ((NI32)(TMP140))))))));
			nimln(262, "parseutils.nim");
			nimln(262, "parseutils.nim");
			hd = (hd * 1.0000000000000000e+01);
			nimln(263, "parseutils.nim");
			i = addInt(i, 1);
			nimln(264, "parseutils.nim");
			while (1) {
				nimln(264, "parseutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA59;
				nimln(264, "parseutils.nim");
				i = addInt(i, 1);
			} LA59: ;
		} LA58: ;
		nimln(265, "parseutils.nim");
		nimln(265, "parseutils.nim");
		(*number) = ((NF64) ((((NF) ((*number))) / hd)));
	}
	LA55: ;
	nimln(267, "parseutils.nim");
	nimln(267, "parseutils.nim");
	if (!(flags == 0)) goto LA61;
	{
		nimln(267, "parseutils.nim");
		nimln(267, "parseutils.nim");
		result = 0;
		goto BeforeRet;
	}
	LA61: ;
	nimln(269, "parseutils.nim");
	nimln(728, "system.nim");
	if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
	if (!(((NU8)(s->data[i])) == ((NU8)(101)) || ((NU8)(s->data[i])) == ((NU8)(69)))) goto LA65;
	{
		nimln(270, "parseutils.nim");
		i = addInt(i, 1);
		nimln(271, "parseutils.nim");
		nimln(271, "parseutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA69;
		{
			nimln(272, "parseutils.nim");
			i = addInt(i, 1);
		}
		goto LA68;
		LA69: ;
		nimln(273, "parseutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(45))) goto LA72;
		{
			nimln(274, "parseutils.nim");
			esign = -1.0000000000000000e+00;
			nimln(275, "parseutils.nim");
			i = addInt(i, 1);
		}
		goto LA68;
		LA72: ;
		LA68: ;
		nimln(276, "parseutils.nim");
		nimln(729, "system.nim");
		nimln(729, "system.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!!((((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57))))) goto LA76;
		{
			nimln(277, "parseutils.nim");
			nimln(277, "parseutils.nim");
			result = 0;
			goto BeforeRet;
		}
		LA76: ;
		nimln(278, "parseutils.nim");
		while (1) {
			NI TMP141;
			NI TMP142;
			NI TMP143;
			nimln(728, "system.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA79;
			nimln(279, "parseutils.nim");
			nimln(279, "parseutils.nim");
			nimln(279, "parseutils.nim");
			nimln(279, "parseutils.nim");
			TMP141 = mulInt(exponent, 10);
			nimln(279, "parseutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			TMP142 = addInt((NI32)(TMP141), ((NI) (((NU8)(s->data[i])))));
			TMP143 = subInt((NI32)(TMP142), 48);
			exponent = (NI32)(TMP143);
			nimln(280, "parseutils.nim");
			i = addInt(i, 1);
			nimln(281, "parseutils.nim");
			while (1) {
				nimln(281, "parseutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA80;
				nimln(281, "parseutils.nim");
				i = addInt(i, 1);
			} LA80: ;
		} LA79: ;
	}
	LA65: ;
	nimln(283, "parseutils.nim");
	hd = 1.0000000000000000e+00;
	j_68429 = 0;
	nimln(1289, "system.nim");
	res_68433 = 1;
	nimln(1290, "system.nim");
	while (1) {
		nimln(1290, "system.nim");
		if (!(res_68433 <= exponent)) goto LA81;
		nimln(1289, "system.nim");
		j_68429 = res_68433;
		nimln(285, "parseutils.nim");
		nimln(285, "parseutils.nim");
		hd = (hd * 1.0000000000000000e+01);
		nimln(1292, "system.nim");
		res_68433 = addInt(res_68433, 1);
	} LA81: ;
	nimln(286, "parseutils.nim");
	nimln(704, "system.nim");
	if (!(0.0 < esign)) goto LA83;
	{
		nimln(286, "parseutils.nim");
		nimln(286, "parseutils.nim");
		(*number) = ((NF64) ((((NF) ((*number))) * hd)));
	}
	goto LA82;
	LA83: ;
	{
		nimln(287, "parseutils.nim");
		nimln(287, "parseutils.nim");
		(*number) = ((NF64) ((((NF) ((*number))) / hd)));
	}
	LA82: ;
	nimln(289, "parseutils.nim");
	nimln(289, "parseutils.nim");
	(*number) = ((NF64) ((((NF) ((*number))) * sign)));
	nimln(290, "parseutils.nim");
	nimln(290, "parseutils.nim");
	TMP144 = subInt(i, start);
	result = (NI32)(TMP144);
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, npuParseFloat)(NimStringDesc* s, NF* number, NI start) {
	NI result;
	NF64 bf;
	nimfr("parseFloat", "parseutils.nim")
	result = 0;
	bf = 0;
	nimln(298, "parseutils.nim");
	result = npuParseBiggestFloat(s, &bf, start);
	nimln(299, "parseutils.nim");
	(*number) = ((NF) (bf));
	popFrame();
	return result;
}
N_NOINLINE(void, parseutilsInit)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();
}

N_NOINLINE(void, parseutilsDatInit)(void) {
}

