/* Generated by Nimrod Compiler v0.9.5 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nimrod -o '/home/matt/MyProjects/Challenges-Nimrod/Classic Algorithms/nimcache/collatz.o' '/home/matt/MyProjects/Challenges-Nimrod/Classic Algorithms/nimcache/collatz.c' */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY91023[4];
N_NIMCALL(NI, collatz_91002)(NI i);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NF, HEX2F_79038)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, write_10463)(FILE* f, NimStringDesc* s);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, readline_10484)(FILE* f);
N_NIMCALL(void, write_10479)(FILE* f, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, parseutilsInit)(void);
N_NOINLINE(void, parseutilsDatInit)(void);
N_NOINLINE(void, strutilsInit)(void);
N_NOINLINE(void, strutilsDatInit)(void);
N_NOINLINE(void, collatzInit)(void);
N_NOINLINE(void, collatzDatInit)(void);
STRING_LITERAL(TMP131, "An integer greater than 1, please: ", 35);
STRING_LITERAL(TMP139, ": ", 2);
STRING_LITERAL(TMP140, "\012", 1);
extern TFrame* frameptr_13038;
NI steps_91010;
NI n_91011;

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result = (NI64)(a % b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

static N_INLINE(NF, HEX2F_79038)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2567, "system.nim");
	nimln(2567, "system.nim");
	nimln(2567, "system.nim");
	nimln(2567, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, collatz_91002)(NI i) {
	NI result;
	nimfr("collatz", "collatz.nim")
	result = 0;
	nimln(4, "collatz.nim");
	{
		NI TMP128;
		NF LOC5;
		nimln(4, "collatz.nim");
		nimln(4, "collatz.nim");
		TMP128 = modInt(i, 2);
		if (!(((NI) ((NI64)(TMP128))) == 0)) goto LA3;
		nimln(5, "collatz.nim");
		nimln(5, "collatz.nim");
		LOC5 = 0;
		LOC5 = HEX2F_79038(i, 2);
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP129;
		NI TMP130;
		nimln(7, "collatz.nim");
		nimln(7, "collatz.nim");
		nimln(7, "collatz.nim");
		TMP129 = mulInt(i, 3);
		TMP130 = addInt((NI64)(TMP129), 1);
		result = (NI64)(TMP130);
	}
	LA1: ;
	nimln(8, "collatz.nim");
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	parseutilsDatInit();
	strutilsDatInit();
	collatzDatInit();
	initStackBottom();
	parseutilsInit();
	strutilsInit();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	collatzInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_NOINLINE(void, collatzInit)(void) {
	nimfr("collatz", "collatz.nim")
	nimln(11, "collatz.nim");
	steps_91010 = 0;
	nimln(13, "collatz.nim");
	write_10463(stdout, ((NimStringDesc*) &TMP131));
	nimln(14, "collatz.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(14, "collatz.nim");
		if (!(n_91011 <= 1)) goto LA1;
		nimln(15, "collatz.nim");
		nimln(15, "collatz.nim");
		LOC2 = 0;
		LOC2 = readline_10484(stdin);
		n_91011 = nsuParseInt(LOC2);
	} LA1: ;
	nimln(17, "collatz.nim");
	while (1) {
		TY91023 LOC9;
		nimln(17, "collatz.nim");
		nimln(17, "collatz.nim");
		if (!!((n_91011 == 1))) goto LA3;
		nimln(18, "collatz.nim");
		{
			TY91023 LOC8;
			nimln(18, "collatz.nim");
			if (!(steps_91010 == 0)) goto LA6;
			nimln(19, "collatz.nim");
			memset((void*)LOC8, 0, sizeof(LOC8));
			nimln(19, "collatz.nim");
			LOC8[0] = nimIntToStr(steps_91010);
			nimln(19, "collatz.nim");
			LOC8[1] = copyString(((NimStringDesc*) &TMP139));
			nimln(19, "collatz.nim");
			LOC8[2] = nimIntToStr(n_91011);
			nimln(19, "collatz.nim");
			LOC8[3] = copyString(((NimStringDesc*) &TMP140));
			write_10479(stdout, LOC8, 4);
		}
		LA6: ;
		nimln(20, "collatz.nim");
		steps_91010 = addInt(steps_91010, 1);
		nimln(21, "collatz.nim");
		n_91011 = collatz_91002(n_91011);
		nimln(22, "collatz.nim");
		memset((void*)LOC9, 0, sizeof(LOC9));
		nimln(22, "collatz.nim");
		LOC9[0] = nimIntToStr(steps_91010);
		nimln(22, "collatz.nim");
		LOC9[1] = copyString(((NimStringDesc*) &TMP139));
		nimln(22, "collatz.nim");
		LOC9[2] = nimIntToStr(n_91011);
		nimln(22, "collatz.nim");
		LOC9[3] = copyString(((NimStringDesc*) &TMP140));
		write_10479(stdout, LOC9, 4);
	} LA3: ;
	popFrame();
}

N_NOINLINE(void, collatzDatInit)(void) {
}

